apiVersion: apps/v1
kind: Deployment
metadata:
  name: depolyment1
spec:
  replicas: 3
  selector:
    matchLabels:
      web: app
  template:
    metadata:
      labels:
        web: app
    spec:
      containers:
      - name: newimages
        image:  ubuntu:latest
        ports:
        - containerPort: 80


-----------------     

kind: apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    web: apps
  ports:
  - port: 4002
    targetPort: 80

