apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: organic-aps-rs
  labels:
    app: 
    key: value
spec:
  replicas: 5 
  selectors:
    matchlabels: 
    web: app
  template:
    metadata:
      labels:
        web: app 
    spec:
      containers:
        - name:  devapp
          image: muralisocial123/organic-app-web-latest
          ports:
            - containerPort:5656
