apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: organic-aps-rs
  labels:
    app: organic-app
spec:
  replicas: 5 
  selector:  
    matchLabels:  
      web: app  
  template:
    metadata:
      labels:
        web: app 
    spec:
      containers:
        - name: devapp
          image: muralisocial123/organic-app-web-latest
          ports:
            - containerPort: 5656
